=== Petrica-Taras/Tkad/etc/dtd/geometry/geometry.dtd
<!ELEMENT ComputationDomain (CoorSys, Points,Lines,Surfaces,Boundary)>
<!ATTLIST ComputationDomain dimension CDATA "2D">
<!ELEMENT CoorSys (CSys*)>
<!ELEMENT CSys (#PCDATA)>
<!ATTLIST CSys id CDATA "global">
<!ATTLIST CSys type CDATA "cartesian">
<!ELEMENT Points (Point*)>
<!ELEMENT Point (#PCDATA)>
<!ATTLIST Point id CDATA "0">
<!ATTLIST Point csys CDATA "global">
<!ELEMENT Lines (Line*)>
<!ELEMENT Line (#PCDATA)>
<!ATTLIST Line id CDATA "0">
<!ATTLIST Line type CDATA "segment">
<!ELEMENT Surfaces (Surface*)>
<!ELEMENT Surface (#PCDATA)>
<!ATTLIST Surface id CDATA "0">
<!ATTLIST Surface points CDATA "0">
<!ATTLIST Surface lines CDATA "0">
<!ELEMENT Boundary (#PCDATA)>

=== Petrica-Taras/Tkad/usr/worked/magnetostatic.project/magnetostatic.geometry.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE ComputationDomain SYSTEM "../../etc/dtd/geometry/geometry.dtd">
<ComputationDomain dimension="2D">
    <CoorSys>
         <CSys id="global" type="cartesian">0.0 0.0</CSys>
    </CoorSys>
	<Points>
		 <!-- id instead of label?-->
	     <Point id="1" csys="global">0.0 0.5</Point>
         <Point id="2" csys="global">0.5 0.0</Point>
         <Point id="3" csys="global">0.5 0.5</Point>
         <Point id="4" csys="global">0.0 0.0</Point>
         <Point id="5" csys="global">1.0 0.5</Point>
         <Point id="6" csys="global">1.5 0.5</Point>
         <Point id="7" csys="global">1.5 0.0</Point>
         <Point id="8" csys="global">1.0 1.0</Point>
         <Point id="9" csys="global">1.5 1.0</Point>
         <Point id="10" csys="global">0.0 1.0</Point>
         <Point id="11" csys="global">0.5 1.0</Point>
         <Point id="12" csys="global">0.0 2.0</Point>
         <Point id="13" csys="global">0.5 2.0</Point>
         <Point id="14" csys="global">0.5 1.5</Point>
         <Point id="15" csys="global">1.0 1.5</Point>
         <Point id="16" csys="global">1.0 2.0</Point>
	</Points>
	<Lines>
	     <Line id="1" type="segment">2 4</Line>
	     <Line id="2" type="segment">1 4</Line>
	     <Line id="3" type="segment">1 3</Line>
	     <Line id="4" type="segment">3 2</Line>
	     <Line id="5" type="segment">2 7</Line>
	     <Line id="6" type="segment">7 6</Line>
	     <Line id="7" type="segment">5 6</Line>
	     <Line id="8" type="segment">5 3</Line>
	     <Line id="9" type="segment">6 9</Line>
	     <Line id="10" type="segment">5 8</Line>
	     <Line id="11" type="segment">3 11</Line>
	     <Line id="12" type="segment">1 10</Line>
	     <Line id="13" type="segment">10 11</Line>
	     <Line id="14" type="segment">8 9</Line>
	     <Line id="15" type="segment">11 14</Line>
	     <Line id="16" type="segment">10 12</Line>
	     <Line id="17" type="segment">14 15</Line>
	     <Line id="18" type="segment">15 16</Line>
	     <Line id="19" type="segment">14 13</Line>
	     <Line id="20" type="segment">13 16</Line>
	     <Line id="21" type="segment">12 13</Line>
	</Lines>
	<Surfaces>
	     <Surface id="1" points="4" lines="4">1 3 2 4 1 2 3 4</Surface>
	     <Surface id="2" points="5" lines="5">2 3 5 6 7 4 5 6 7 8</Surface>
	     <Surface id="3" points="4" lines="4">5 6 9 8 7 9 14 10</Surface>
	     <Surface id="4" points="4" lines="4">1 3 11 10 3 11 13 12</Surface>
	     <Surface id="5" points="5" lines="5">10 11 14 13 12 13 15 19 21 16</Surface>
	     <Surface id="6" points="4" lines="4">14 15 16 13 19 18 17 20</Surface>
	</Surfaces>
	<Boundary>1 5 6 9 14 10 8 11 15 17 18 20 21 16 12 2</Boundary>
</ComputationDomain>
